### ISSUE TITLE
Discord Invite invalid

### ISSUE THREAD

**Issue by Kumicoo** [reiichi001/project-meteor-mirror#1]
Hey there.

The Discord invite is invalid.

I just wanted to ask if this is, as i understand, something that allows me to play the original ff14 1.23b in singleplayer and how that would work with party-content.

Thanks!

**Comment by reiichi001** [comment]
The discord invite was purposely revoked because spambots were flooding the server. I've updated the readme here to direct to the project's main repository, as this is just a mirror on github for people who don't want to use bitbucket for any reason. 

This mirror will likely be out of date most of the time.

While Project MEteor is a server emulator project, it's not a "make it singleplayer" project. It also has extremely little content implemented because the underlying systems for most game content still need to be implemented.
